version: '3'

includes:
  ledger-svc:
    taskfile: services/ledger-svc/Taskfile.yml
    dir: services/ledger-svc

tasks:
  test-all:
    desc: Run tests for all projects
    cmds:
      - task api:test